print("Bienvenido al Survival Guide")
print("A continuación se mostraran los 4 nieveles que debes pasar")
print("============")
print("La Cámara de las Reglas: Donde se explican las normas de convivencia y asistencia.")
print("============")
print("El Oráculo de las Notas: Donde se detallan los porcentajes de evaluación.")
print("============")
print("Skills a desbloquear: Aquí se detallan el objetivo general y particular de la materia")
print("============")
print("La Línea del Tiempo: Donde se muestran las fechas clave del semestre.")
print("============")
print("Felicidades, haz sobrevivido... por el momento")